name: Build Spout Shadow

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive   # подтягивает lib/Spout2 как сабмодуль

    - name: Build the mod
      uses: geode-sdk/build-geode-mod@main
      id: build
      with:
        sdk: 'given'             # берёт 5.7.1 из mod.json → "geode" поле
        build-config: RelWithDebInfo
        export-pdb: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SpoutShadow.geode
        path: ${{ steps.build.outputs.build-output }}
        if-no-files-found: error