name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize and Update Submodules
        run: git submodule update --init --recursive

      - name: Setup Geode CLI
        uses: geode-sdk/action@main
        with:
          cli: latest
          sdk: 5.7.1

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package Mod
        run: |
          cd build
          cpack -C Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gd_spout_mod
          path: build/*.geode
